MODULE conhyp_m
  USE constants, ONLY: RP
  IMPLICIT NONE

  INTERFACE

    ELEMENTAL COMPLEX(RP) MODULE FUNCTION conhyp(A,B,Z,LNCHF,IP)
      COMPLEX(RP), INTENT(IN) :: A, B, Z
      INTEGER, INTENT(IN) :: Lnchf, IP
    END FUNCTION conhyp

  END INTERFACE

END MODULE conhyp_m