MODULE conhyp_m
  USE constants, ONLY: RP
  IMPLICIT NONE

  INTERFACE

    COMPLEX(RP) MODULE FUNCTION CONHYP (A,B,Z,LNCHF,IP)
      COMPLEX(RP), INTENT(IN) :: A, B, Z
      INTEGER, INTENT(IN), OPTIONAL :: LNCHF, IP
    END FUNCTION CONHYP

  END INTERFACE

END MODULE conhyp_m
