name: Build

on:
  push:
  schedule:
    - cron: '0 8 * * 0'

jobs:
  GNU:
    name: GNU-${{ matrix.gnu_ver }}-${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        gnu_ver: [11, 12]
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
      - name: Install gfortran
        run: |
          sudo apt install -y gfortran-${{ matrix.gnu_ver }}
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=gfortran-${{ matrix.gnu_ver }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: make -C build -j$(nproc)
      - name: Running
        run: |
          cd build
          mv input_example.dat input.dat
          ./main
          ./main cw
          ./main dw
          ./main dwb

  Intel:
    name: Intel-${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Intel compilers
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt install --no-install-recommends intel-oneapi-compiler-fortran
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: make -C build -j$(nproc)
      - name: Running
        run: |
          cd build
          mv input_example.dat input.dat
          ./main
          ./main cw
          ./main dw
          ./main dwb

  Nvidia:
    name: Nvidia-${{ matrix.build_type }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nvidia HPC Compiler
        run: |
          echo "deb [trusted=yes] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /" > nvhpc.list
          sudo cp nvhpc.list /etc/apt/sources.list.d/
          sudo apt-get update
          sudo apt-get install -y nvhpc-22-7
          echo "/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/22.7/compilers/lib" >> $GITHUB_ENV
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_Fortran_COMPILER=nvfortran \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: make -C build -j$(nproc)
      - name: Running
        run: |
          cd build
          mv input_example.dat input.dat
          ./main
          ./main cw
          ./main dw
          ./main dwb
